### ISSUE TITLE
How can we save/export manually all snippets ?

### ISSUE THREAD

**Issue by yuyuki** [devon2018/snippet#11]
Hello,

I really appreciate this extension but I would really like to know how I can save all my snippets.

Thank for your job and for the answer

**Comment by jimrandell** [comment]
Hi, 
(Great job, love the extension)

I have been looking for same....or more specifically, I would like to know where the snippets are stored, so I can edit them in the file.

I really want to use Snippet, but this is the blocker. I hope you can take a minute to reply!

THANKS!!!!

**Comment by devon2018** [comment]
HI @yuyuki At the moment it's not possible to export snippets, this is a feature i've been working on and it will be ready in the next few weeks.

**Comment by devon2018** [comment]
Hi @jimrandell 

Thank you :)

At the moment snippets are stored in vscodes global state, and not in a file so it's not possible to edit manually. but in my last release i have added the ability to edit snippets. you can do this by right clicking on any snippet.

**Comment by devon2018** [comment]
It is now possible to import / export snippets, please see the readme for more info.
