### ISSUE TITLE
How can we use placeholder ?

### ISSUE THREAD

**Issue by yuyuki** [devon2018/snippet#12]
Hi,

I've now plenty of snippets :) thank again

I wonder now how can I use placeholder ?

By the way, all link to your youtube video does not work. All video are private

Have a nice day

**Comment by devon2018** [comment]
Hi @yuyuki 

Thanks for letting me know about the videos, I completely missed that. They should all be public now :)

With regards to placeholders, it's something that i would like to add but i don't see how it would be possible. As far as i know it's not possible to handle tabs like regular vscode snippets do. 

Thanks
