### ISSUE TITLE
New Suggestion : search in case Insensitive

### ISSUE THREAD

**Issue by yuyuki** [devon2018/snippet#13]
Hi,

When I enter the name of a snippet. It works only if I respect the case. It would be easier to make a search base on insensitive caracter.

Is it possible ?

**Comment by devon2018** [comment]
Hi @yuyuki 

Can you double check this, I've tried to replicate but i seem to be able to search fine it doesn't seem to be case sensitive.

Thanks, Devon

**Comment by devon2018** [comment]
I'm closing this is I can't seem to replicate.

**Comment by yuyuki** [comment]
Sorry, I didn't answer.

Yes, you're right. It's case insensitive.
