### ISSUE TITLE
Snippets not accessible until I click on snippets tab

### ISSUE THREAD

**Issue by kustomjulius** [devon2018/snippet#24]
This is a fantastic extension, getting a lot of good use out of it. I'm having a problem where none of my created snippets are accessible in the IDE until I click on the snippets tab then go back and try again, is anyone else having this issue?

Thanks again for this awesome tool!

**Comment by devon2018** [comment]
Hi @kustomjulius 

I have actually noticed this as well recently, I am planning an update over the few weeks and will look into creating a fix for this.

**Comment by kustomjulius** [comment]
> Hi @kustomjulius
> 
> I have actually noticed this as well recently, I am planning an update over the few weeks and will look into creating a fix for this.

Sounds good, thank you again for all your hard work :)

**Comment by devon2018** [comment]
This has now been resolved in the next update using the suggestion above.
