### ISSUE TITLE
Snippet modal preview window (Feature request)

### ISSUE THREAD

**Issue by zbahadir** [devon2018/snippet#34]
**Snippet preview**
Before we make the code snippet, we want to see its content. May be useful for similar content.

![snippet_view](https://user-images.githubusercontent.com/3078225/149660711-91e81d1a-fed4-4d4d-9aeb-f929e7edc735.png)

**Comment by souhailmerroun** [comment]
+1

**Comment by devon2018** [comment]
Hi @zbahadir 

This is a great idea, i'll have a play around and see if vscode offers a way to do this, let me know if you've seen any other plugins that do something similar.

**Comment by zbahadir** [comment]
> 
Hi,
I think I found a few examples. If I had time, I would like to try it myself, but I work very hard.

[https://marketplace.visualstudio.com/items?itemName=avraammavridis.vsc-react-documentation](url)
[https://marketplace.visualstudio.com/items?itemName=nortakales.date-hover-preview](url)
[https://marketplace.visualstudio.com/items?itemName=ltaoo.vscode-plugin-image-hover-preview](url)
[https://marketplace.visualstudio.com/items?itemName=tintinweb.vscode-ethover](url)

**Comment by zbahadir** [comment]
I think this plugin includes the feature we want.
https://marketplace.visualstudio.com/items?itemName=MeshIntelligentTechnologiesInc.pieces-vscode

**Comment by mask2012** [comment]
Yes，we need this feature so much, if popover needs lots of time, an extra button click is also acceptable, because right click -> edit  is low efficient, and preview code is a high frequency operation.
and this may need 30min of work, but you saved us lots of time, will very appriciate that!

**Comment by devon2018** [comment]
Update now available with this included.
