### ISSUE TITLE
Allow deleting all existing snippets for clean importing of a new snippet dataset

### ISSUE THREAD

**Issue by carloscadux** [devon2018/snippet#38]
**Is your feature request related to a problem? Please describe.**
I export all snippets to snippets.json, performing several minor editing in specific snippets, and editing in batches regarding tags.
Then I imported snippets.json back, and go several duplicates, since the current snippets dataset and the new edited one got merged.

**Describe the solution you'd like**
Allow deleting all existing snippets (single command) for clean importing of a new snippet dataset.

Thank you!

**Comment by devon2018** [comment]
Thanks for the comment, will consider this for the next update.
