### ISSUE TITLE
Decreasing the font size of the 'edit' snippet dialog (currently too big)

### ISSUE THREAD

**Issue by carloscadux** [devon2018/snippet#40]
**Is your feature request related to a problem? Please describe.**
The font size of the 'edit' snippet dialog is too big (screenshot below)

**Describe the solution you'd like**
Please, consider decreasing the font size of the 'edit' snippet dialog.

Thank you!

![image](https://user-images.githubusercontent.com/7339389/156542732-250466c9-a79c-4f47-a3fa-d8a6900f9235.png)

**Comment by devon2018** [comment]
Thanks for the comment, will consider this for the next update.

**Comment by devon2018** [comment]
Update now available with this included.
