### ISSUE TITLE
Sort snippets by alphabetic order

### ISSUE THREAD

**Issue by Maxensation** [devon2018/snippet#43]
it will be awesome to be able to sort snippets by alphabetic order

**Comment by benjezza** [comment]
bump :)

**Comment by devon2018** [comment]
Thanks for your comment, Will consider this for the next release :)

**Comment by benjezza** [comment]
Thanks @devon2018 , any chance during the interim that you could let us know which file the snippets are stored in, so we can sort them manually?

**Comment by ArrushC** [comment]
I'm not sure if you have found the answer but if you click on `Ctrl + Shift + P` and go to Export Snippets, there's a file called `snippets.json`.

**Comment by benjezza** [comment]
> I'm not sure if you have found the answer but if you click on `Ctrl + Shift + P` and go to Export Snippets, there's a file called `snippets.json`.

Thanks ArrushC, I had found that and it works great for the "Editor" snippets, however, doesnt include the terminal snippets.

**Comment by devon2018** [comment]
Update now available with this included.
