### ISSUE TITLE
Text color error when using Dark High Contrast color theme.

### ISSUE THREAD

**Issue by KFC0803** [devon2018/snippet#44]
| snippet Version | Operating System |
| --------------- | ---------------- |
|1.0.3|Windows 11|

# Description

## Expected Behavior

![Snipaste_2022-07-24_09-30-49](https://user-images.githubusercontent.com/22217328/180628620-41d412cc-32b2-4aab-a243-4478a1db60e3.png)
![Snipaste_2022-07-24_09-35-02](https://user-images.githubusercontent.com/22217328/180628622-2ab0ea89-682f-4d92-ad7e-f7b6a1198118.png)
And custom fonts do not work. 
## Actual Behavior

Text color is supposed to be white here. I also changed editor font in VS Code setting.

**Comment by devon2018** [comment]
I think this may be a bug with either vscode or the theme you are using as I am not currently handling the colour of that its all done through vscode
