### ISSUE TITLE
how to delete a snippet ? 

### ISSUE THREAD

**Issue by aniketash57** [devon2018/snippet#45]
hey I am using your extension but not able to understand how to delete and edit a snippet can you upload a guide related to that ?

**Comment by devon2018** [comment]
You can edit and delete snippets by right clicking on them in the sidebar and choosing either edit or delete
<img width="416" alt="Screenshot 2022-08-16 at 22 25 28" src="https://user-images.githubusercontent.com/46196252/184987975-659433da-9e0b-479a-9af1-8a46a5124f1e.png">

**Comment by robozb** [comment]
> You can edit and delete snippets by right clicking on them in the sidebar and choosing either edit or delete <img alt="Screenshot 2022-08-16 at 22 25 28" width="416" src="https://user-images.githubusercontent.com/46196252/184987975-659433da-9e0b-479a-9af1-8a46a5124f1e.png">

Now it doesn't work :(


https://github.com/devon2018/snippet/assets/8656998/1c4d94d2-3051-42cd-b33c-8bd9c4823331
