### ISSUE TITLE
Location of the created snippets?

### ISSUE THREAD

**Issue by robozb** [devon2018/snippet#48]
Thank you!

VSCode:

Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by devon2018** [comment]
Snippets are stored in the vscode state not in a file, you can export the snippets json file though

**Comment by robozb** [comment]
OK, thank you so much!  This is missing from the documentation in VSCode.

![Here](https://user-images.githubusercontent.com/8656998/211413223-1d92b099-c62b-4641-ae45-3da7b4cf1210.JPG)

**Comment by robozb** [comment]
Thanks for this cool extension!
