### ISSUE TITLE
Grouping of Snippets

### ISSUE THREAD

**Issue by JoeyUson** [devon2018/snippet#50]
**Is your feature request related to a problem? Please describe.**
In your youtube video it is possible to create a group by entering group+subgroup , however with V1.1 it will only appear in search function but the groups will only shows base on program extension.

**Describe the solution you'd like**
I'm using MQL4/MQL5 and the program syntax is CPP. So if I create program for Arduino it will go under CPP group as well
It would be better if it appear as group not only during search

**Describe alternatives you've considered**
Having it arrange based in App Type would clearly makes it neat by segregation based in application and not in program language extension or sysntax

**Additional context**

**Comment by devon2018** [comment]
Hi @JoeyUson 

I go based on the code type detected in the created snippet, unfortunately its not possible to detect your app type from that, only the language that is used.

Best thing would be a tag with your app type and use the search functionality to access matching snippets.
