### ISSUE TITLE
Sync "New" Snippets across Multiple Running VSCode Instances/Windows

### ISSUE THREAD

**Issue by sodonnell** [devon2018/snippet#52]
**Is your feature request related to a problem? Please describe.**
I typically have about 2-5 instances of VSCode running simultaneously, but when I add a new snippet to one of my editor instances, that new snippet doesn't appear in my other actively running VSCode instance until I restart VSCode.

**Describe the solution you'd like**
Somehow "sync" or "share" newly added snippets across all active VSCode sessions/windows.

**Describe alternatives you've considered**
N/A

**Additional context**
Great extension! Hopefully this feature can be added or worked-out. It would greatly reduce frustration and increase productivity. I'm sure I'm not alone on this one.

Thank you,
Sean

**Comment by devon2018** [comment]
Hi @sodonnell 

Because of how snippets are stored this will not be possible.

I would consider creating a workspace for your projects so you don't need to have multiple vscode windows open and have sync issues. Think thats how most people would develop with multiple codebases.
