### ISSUE TITLE
Option to edit snippet after 

### ISSUE THREAD

**Issue by smjure** [devon2018/snippet#6]
Would be great if one is able to modify/edit snippets, i.e. prefix, body and description after a snippet is created!
Thank you, keep up with the great work!

**Comment by devon2018** [comment]
Hi @smjure 

This is something I plan to include, but haven't quite figured out a good way of doing it. Will let you know when it's added :)

**Comment by benjezza** [comment]
for now, where are the snippets saved, so that we can do it manually?

**Comment by devon2018** [comment]
@benjezza the best way to edit snippets at the moment would be to insert it into a file and re add it as they currently all get stored in the vscode globalState. The ability to update is coming soon, i am working on it along with a few other features that should be ready in the next week.

**Comment by mean-cj** [comment]
Hello @devon2018 

your extension is excellent. , thank you so much.

I vote can manual edit/modify
- edit snippet content
- rename tag name
- rename note list name
  : )

**Comment by benjezza** [comment]
Keep up the good work, looking forward to the updates!

**Comment by devon2018** [comment]
A new version of the plugin has now been released with the ability to edit a snippet currently on the title and content is editable.
