### ISSUE TITLE
Add support for terminal snippets

### ISSUE THREAD

**Issue by devon2018** [devon2018/snippet#8]

**Comment by mean-cj** [comment]
Hello @devon2018 

You can try send snippet to terminal

```
const vscode = require('vscode');

const snippet_command = "echo 1";
let hasTerminal = vscode.window.terminals.length;

if( ! hasTerminal )
{
  vscode.window.createTerminal({ name: 'Command' });
}

if (vscode.window.activeTerminal) {
	vscode.window.activeTerminal.show();
	vscode.window.activeTerminal.sendText(snippet_command);
}
```

**Comment by devon2018** [comment]
Thanks @mean-cj 

So i've started working on this feature in the last week, I will try and use the code you've given as much as possible, however vscode doesnt allow much interaction from the integrated terminal in terms of grabbing the highlighted text, so i'm still trying to find the best way to do that.

**Comment by mean-cj** [comment]
I think that's enough , 

user can create a snippet from editor.

when need to use click snippet list send to editor or ctrl+click send to terminal

or choose "send to" on snippet context menu

It's easier for development

**Comment by devon2018** [comment]
Support for terminal snippets has now been added in version 0.1.0.
